# SQLite for development and test
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

production:
  primary:
    adapter: postgresql
    encoding: unicode
    database: gerenciador_cadastros_production
    username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
    password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
    host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
    port: <%= ENV.fetch("DATABASE_PORT", "5432") %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  cache:
    <<: *default
    database: gerenciador_cadastros_cache_production
    username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
    password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: gerenciador_cadastros_queue_production
    username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
    password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: gerenciador_cadastros_cable_production
    username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
    password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
    migrations_paths: db/cable_migrate
