# PostgreSQL configuration
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "" } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>

development:
  <<: *default
  database: gerenciador_cadastros_development

test:
  <<: *default
  database: gerenciador_cadastros_test

production:
  primary:
    <<: *default
    database: gerenciador_cadastros_production
    username: <%= ENV.fetch("DATABASE_USERNAME") %>
    password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  cache:
    <<: *default
    database: gerenciador_cadastros_cache_production
    username: <%= ENV.fetch("DATABASE_USERNAME") %>
    password: <%= ENV.fetch("DATABASE_PASSWORD") %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: gerenciador_cadastros_queue_production
    username: <%= ENV.fetch("DATABASE_USERNAME") %>
    password: <%= ENV.fetch("DATABASE_PASSWORD") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: gerenciador_cadastros_cable_production
    username: <%= ENV.fetch("DATABASE_USERNAME") %>
    password: <%= ENV.fetch("DATABASE_PASSWORD") %>
    migrations_paths: db/cable_migrate
